#
# Copyright 1996-2001 by the President and Fellows of Harvard College.
# See LICENSE.txt for license information.
#
# Makefile for .../Src/ programs
#
# targets:
# all (default): builds everything
# clean

all:
	cd AntCommon ;	$(MAKE) $@
	cd Ant8 ;	$(MAKE) $@
	cd Ant32 ;	$(MAKE) $@

clean:
	cd AntCommon ;	$(MAKE) $@
	cd Ant8 ;	$(MAKE) $@
	cd Ant32 ;	$(MAKE) $@

# end of Makefile
